version: '3.7'

services:

  node:
    build: ./backand
    image: myapp-server
    container_name: myapp-node-serverx
    restart: always
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb+srv://UtsavDesai:Utsav_*_26@cluster0.dasho2p.mongodb.net/?retryWrites=true&w=majority
    networks:
      - app-network

  mongodb:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network


  react:
    build: .
    image: myapp-client
    container_name: myapp-react-client
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - node
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
